services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: es_web_service
    ports:
      - "5432:5432"
    volumes:
      - es-db:/var/lib/postgresql/data
    restart: always

  web-service:
    build: ./web-service
    environment:
      NODE_ENV: production
      PORT: 1337
      DB_URI: postgres://postgres:postgres@postgres:5432
      DB_HOST: postgres
      DB_NAME: es_web_service
      JWT_SECRET: secure
      CONTROL_ALGO_PATH: main.py
      OPEN_WEATHER_API_KEY: dfc57d64f0ddb809798fd887679e92f8
    depends_on:
      - postgres
    ports:
      - "1337:1337"
    restart: always

  web-app:
    build: ./web-app
    depends_on:
      - web-service
    ports:
      - "1338:80"
    restart: always

volumes:
  es-db:
